version: "3"
services:
  node-build:
    image: node:8.16.0-alpine
    volumes:
      - ./:/data/fe-paas
    working_dir: /data/fe-paas
    entrypoint: |
      /bin/sh -c "yarn \
      && npm run build \
      && cd deploy/fe-paas 
      && npm install"
  spa-server:
    build:
      context: .
    image: harbor.finupgroup.com/galaxy/spa-server:v1.0






