version: "3"
services:
  node-build:
    image: node:8.16.0-alpine
    volumes:
      - ./:/data/fe-paas
    working_dir: /data/fe-paas
    entrypoint: |
      /bin/sh -c "yarn \
      && npm run build \
      && cd deploy/fe-paas 
      && npm install"
  fe-paas:
    build:
      context: .
    image: harbor.finupgroup.com/galaxy/fe-paas:latest
    restart: on-failure
    ports:
      - "6001:6001"
    networks:
      - spa_net
    environment:
      - NODE_ENV=production
      - PORT=6001
      - LOG_DIR=/data/fe-paas/logs
      - DEBUG=fe-paas
      - LOG_FILE_NAME=fe-paas

    volumes:
      - ./logs:/data/fe-paas/logs

networks:
  spa_net:
    ipam:
      driver: default
      config:
        - subnet: "172.29.2.0/24"
